#ifndef _SYSCALL_NB_COMMON_H_
#define _SYSCALL_NB_COMMON_H_

typedef enum { 
    SYSCALL_TERM_PUTS = 0,
    SYSCALL_TERM_SET_COLORS,
    SYSCALL_KEYB_GET_KEY,
    SYSCALL_TIMER_INFO,
    SYSCALL_TIMER_SLEEP,
    SYSCALL_VBE_FB_INFO,
    SYSCALL_VBE_SETPIX,
    SYSCALL_TASK_EXEC,
    __SYSCALL_END__
} syscall_t;

#endif
